package com.vailsys.freeclimb.api.phoneNumber;

import com.google.gson.JsonSyntaxException;
import com.vailsys.freeclimb.api.APIAccountRequester;
import com.vailsys.freeclimb.api.FreeClimbException;
import com.vailsys.freeclimb.api.FreeClimbJSONException;

import java.util.HashMap;

import static com.vailsys.freeclimb.json.FreeClimbGson.gson;

/**
 * This class represents the set of wrappers around the FreeClimb
 * IncomingPhoneNumbers API It provides methods to handle all the operations
 * supported by the FreeClimb IncomingPhoneNumbers API.
 */
public class IncomingPhoneNumberRequester extends APIAccountRequester {
    private static final String pathHead = "IncomingPhoneNumbers";
    /** The default path for the IncomingPhoneNumbers endpoint. */
    private final String path;
    /** The accountId for the acting account. */
    private final String actingAccountId;

    /**
     * Creates an IncomingPhoneNumberRequester. For most SDK users
     * IncomingPhoneNumberRequesters will be created automatically by the
     * {@link com.vailsys.freeclimb.api.FreeClimbClient} but is available for more
     * advanced users who only require the features in this specific requester and
     * not the rest of the features of the
     * {@link com.vailsys.freeclimb.api.FreeClimbClient}.
     *
     * @param credAccountId   The accountId to use as authentication credentials in
     *                        the HTTP Basic Auth header for requests made by this
     *                        requester.
     * @param credApiKey   The apiKey to use as authentication credentials in
     *                        the HTTP Basic Auth header for requests made by this
     *                        requester.
     * @param actingAccountId The accountId to act as. This can be the same as
     *                        {@code credAccountId} or the accountId of a subaccount
     *                        of the {@code credAccountId}.
     */
    public IncomingPhoneNumberRequester(String credAccountId, String credApiKey, String actingAccountId) {
        super(credAccountId, credApiKey);
        this.actingAccountId = actingAccountId;
        this.path = APIAccountRequester.constructPath(APIAccountRequester.rootPath, this.actingAccountId, pathHead);
    }

    /**
     * Retrieve the {@code path} value generated by the
     * IncomingPhoneNumberRequester. This is the URL path used in requests to
     * FreeClimb.
     *
     * @return The {@code path}.
     */
    public String getPath() {
        return path;
    }

    private String getIncomingPhoneNumberPath(String incomingPhoneNumberId) {
        return APIAccountRequester.constructPath(this.getPath(), incomingPhoneNumberId);
    }

    /**
     * Retrieve the {@code actingAccountId}.
     *
     * @return The {@code actingAccountId}.
     */
    public String getActingAccountId() {
        return actingAccountId;
    }

    /**
     * Allows developers using the SDK to change which instance of the FreeClimb API
     * that the IncomingPhoneNumberRequester points to.
     *
     * @param newUrl The new URL to use in place of the default
     *               APIRequester.FREECLIMB_URL
     */
    public void setFreeClimbUrl(String newUrl) {
        super.setFreeClimbUrl(newUrl);
    }

    /**
     * Retrieve a list of IncomingPhoneNumbers associated with the
     * {@code actingAccountId}. This wraps a HTTP GET request to the FreeClimb API's
     * /Accounts/$accountId/IncomingPhoneNumbers endpoint. This will retrieve all
     * incoming phone numbers for the acting account.
     *
     * @return An in-language representation of FreeClimb's paginated list response.
     *         This will be a paginated list of incoming phone numbers as returned
     *         by the FreeClimb API.
     * @throws FreeClimbException when the request fails or the JSON is invalid.
     */
    public IncomingPhoneNumberList get() throws FreeClimbException {
        return new IncomingPhoneNumberList(this.getCredentialAccountId(), this.getCredentialApiKey(),
                this.GET(this.getPath()));
    }

    /**
     * Retrieve a list of IncomingPhoneNumbers associated with the
     * {@code actingAccountId}. This wraps a HTTP GET request to the FreeClimb API's
     * /Accounts/$accountId/IncomingPhoneNumbers endpoint. This will retrieve all
     * incoming phone numbers for the acting account.
     *
     * @param filters an object containing a number of possible ways to filter the
     *                incoming phone numbers returned by FreeClimb.
     *
     * @see com.vailsys.freeclimb.api.phoneNumber.IncomingPhoneNumberSearchFilters
     * @return An in-language representation of FreeClimb's paginated list response.
     *         This will be a paginated list of incoming phone numbers as returned
     *         by the FreeClimb API.
     * @throws FreeClimbException when the request fails or the JSON is invalid.
     */
    public IncomingPhoneNumberList get(IncomingPhoneNumberSearchFilters filters) throws FreeClimbException {
        HashMap<String, String> filtersMap;

        try {
            filtersMap = gson.fromJson(gson.toJson(filters), APIAccountRequester.GETMapType);
        } catch (JsonSyntaxException jse) {
            throw new FreeClimbJSONException(jse);
        }

        return new IncomingPhoneNumberList(this.getCredentialAccountId(), this.getCredentialApiKey(),
                this.GET(this.getPath(), filtersMap));
    }

    /**
     * Create a new incoming phone number through the FreeClimb API. This function
     * wraps an HTTP POST request to the FreeClimb API's
     * /Account/$accountId/IncomingPhoneNumbers endpoint. This purchases a new
     * incoming phone number under the {@code actingAccountId}'s account.
     *
     * @param options Optional arguments that can be provided when creating an
     *                Incoming Phone Number. See FreeClimb documentation for
     *                details.
     * @see com.vailsys.freeclimb.api.phoneNumber.IncomingPhoneNumberCreateOptions
     * @return The {@link com.vailsys.freeclimb.api.phoneNumber.IncomingPhoneNumber}
     *         object returned by FreeClimb that represents the incoming phone
     *         number that was created.
     * @throws FreeClimbException when the request fails or the JSON is invalid.
     */
    public IncomingPhoneNumber create(IncomingPhoneNumberCreateOptions options) throws FreeClimbException {
        return IncomingPhoneNumber.fromJson(this.POST(this.getPath(), gson.toJson(options)));
    }

    /**
     * Remove the incoming phone number with a matching
     * {@code incomingPhoneNumberId} as an incoming number. FreeClimb will no longer
     * answer calls to the number. This function wraps an HTTP DELETE request to the
     * /Account/$accountId/IncomingPhoneNumbers/$incomingPhoneNumberId endpoint.
     *
     * @param incomingPhoneNumberId The id of the incoming phone number to delete.
     * @throws FreeClimbException when the request fails or the JSON is invalid.
     */
    public void delete(String incomingPhoneNumberId) throws FreeClimbException {
        this.DELETE(this.getIncomingPhoneNumberPath(incomingPhoneNumberId));
    }

    /**
     * Retrieve a single incoming phone number from FreeClimb.
     *
     * @param incomingPhoneNumberId The {@code incomingPhoneNumberId} of the desired
     *                              incoming phone number.
     * @return The incoming phone number matching the {@code incomingPhoneNumberId}
     *         provided.
     * @throws FreeClimbException when the request fails or the JSON is invalid.
     */
    public IncomingPhoneNumber get(String incomingPhoneNumberId) throws FreeClimbException {
        return IncomingPhoneNumber.fromJson(this.GET(this.getIncomingPhoneNumberPath(incomingPhoneNumberId)));
    }

    /**
     * Update the existing incoming phone number associated with the
     * {@code incomingPhoneNumberId}. This wraps an HTTP POST request to the
     * FreeClimb API's
     * /Accounts/$accountId/IncomingPhoneNumbers/$incomingPhoneNumberId endpoint.
     *
     * @param incomingPhoneNumberId The {@code incomingPhoneNumberId} of the desired
     *                              incoming phone number.
     * @param options               The {@code IncomingPhoneNumberUpdateOptions} to
     *                              change in the target IncomingPhoneNumber.
     * @return The incoming phone number matching the {@code incomingPhoneNumberId}
     *         provided.
     * @throws FreeClimbException when the request fails or the JSON is invalid.
     */
    public IncomingPhoneNumber update(String incomingPhoneNumberId, IncomingPhoneNumberUpdateOptions options)
            throws FreeClimbException {
        return IncomingPhoneNumber
                .fromJson(this.POST(this.getIncomingPhoneNumberPath(incomingPhoneNumberId), gson.toJson(options)));
    }
}
